//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebApplication.TextFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TextFileService.DemoWebServiceSoap")]
    public interface DemoWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveText", ReplyAction="*")]
        CalculatorWebApplication.TextFileService.SaveTextResponse SaveText(CalculatorWebApplication.TextFileService.SaveTextRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveText", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebApplication.TextFileService.SaveTextResponse> SaveTextAsync(CalculatorWebApplication.TextFileService.SaveTextRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveTextRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveText", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.TextFileService.SaveTextRequestBody Body;
        
        public SaveTextRequest() {
        }
        
        public SaveTextRequest(CalculatorWebApplication.TextFileService.SaveTextRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveTextRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string text;
        
        public SaveTextRequestBody() {
        }
        
        public SaveTextRequestBody(string text) {
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveTextResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveTextResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.TextFileService.SaveTextResponseBody Body;
        
        public SaveTextResponse() {
        }
        
        public SaveTextResponse(CalculatorWebApplication.TextFileService.SaveTextResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveTextResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SaveTextResult;
        
        public SaveTextResponseBody() {
        }
        
        public SaveTextResponseBody(bool SaveTextResult) {
            this.SaveTextResult = SaveTextResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DemoWebServiceSoapChannel : CalculatorWebApplication.TextFileService.DemoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DemoWebServiceSoapClient : System.ServiceModel.ClientBase<CalculatorWebApplication.TextFileService.DemoWebServiceSoap>, CalculatorWebApplication.TextFileService.DemoWebServiceSoap {
        
        public DemoWebServiceSoapClient() {
        }
        
        public DemoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebApplication.TextFileService.SaveTextResponse CalculatorWebApplication.TextFileService.DemoWebServiceSoap.SaveText(CalculatorWebApplication.TextFileService.SaveTextRequest request) {
            return base.Channel.SaveText(request);
        }
        
        public bool SaveText(string text) {
            CalculatorWebApplication.TextFileService.SaveTextRequest inValue = new CalculatorWebApplication.TextFileService.SaveTextRequest();
            inValue.Body = new CalculatorWebApplication.TextFileService.SaveTextRequestBody();
            inValue.Body.text = text;
            CalculatorWebApplication.TextFileService.SaveTextResponse retVal = ((CalculatorWebApplication.TextFileService.DemoWebServiceSoap)(this)).SaveText(inValue);
            return retVal.Body.SaveTextResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebApplication.TextFileService.SaveTextResponse> CalculatorWebApplication.TextFileService.DemoWebServiceSoap.SaveTextAsync(CalculatorWebApplication.TextFileService.SaveTextRequest request) {
            return base.Channel.SaveTextAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebApplication.TextFileService.SaveTextResponse> SaveTextAsync(string text) {
            CalculatorWebApplication.TextFileService.SaveTextRequest inValue = new CalculatorWebApplication.TextFileService.SaveTextRequest();
            inValue.Body = new CalculatorWebApplication.TextFileService.SaveTextRequestBody();
            inValue.Body.text = text;
            return ((CalculatorWebApplication.TextFileService.DemoWebServiceSoap)(this)).SaveTextAsync(inValue);
        }
    }
}
